// Code generated by herramientas/generar_roles.py. DO NOT EDIT.
//
// La lista de roles del Reglamento vive en
// `motor/src/actaira_motor/roles.py` y este fichero se genera de ella.
//
// Estaba escrita a mano aqui y estaba MAL: decia
// `responsable_del_despliegue` y `fabricante_de_productos` donde el motor
// dice `responsable_despliegue` y `fabricante_producto`, y le faltaba
// `proveedor_modelo` entero. Como esta lista era ademas la validacion de
// entrada de la API, el efecto no era rechazar el rol equivocado: era
// ACEPTARLO y pasarselo al motor, que no lo reconocia y devolvia cero
// obligaciones aplicables. La validacion confirmaba el error en vez de
// cazarlo, que es lo peor que puede hacer una validacion.

package api

// RolesDelReglamento son los identificadores de rol que el motor entiende.
// El orden es el de la fuente y se mantiene para que el diff sea legible.
var RolesDelReglamento = []string{
	// proveedor (articulo 3.3)
	"proveedor",
	// responsable del despliegue (articulo 3.4)
	"responsable_despliegue",
	// representante autorizado (articulo 3.5)
	"representante_autorizado",
	// importador (articulo 3.6)
	"importador",
	// distribuidor (articulo 3.7)
	"distribuidor",
	// fabricante de productos (articulo 25.3)
	"fabricante_producto",
	// proveedor de modelo de uso general (articulo 53)
	"proveedor_modelo",
}

// RolConocido dice si el identificador esta en el vocabulario.
func RolConocido(rol string) bool {
	for _, r := range RolesDelReglamento {
		if r == rol {
			return true
		}
	}
	return false
}
