r"""Genera los DERIVADOS del vocabulario de roles. La fuente es `roles.py`.

POR QUE SE GENERA Y NO SE ESCRIBE
-----------------------------------
Habia cuatro listas de roles escritas por separado -- el catalogo, el motor, la
API en Go y el panel en JavaScript -- y dos estaban mal. El panel mandaba
`responsable_del_despliegue`, la API lo validaba contra su propia lista, que
tenia el mismo error, y lo dejaba pasar; el motor no reconocia ese nombre y le
contestaba a un responsable del despliegue real que no le ataba ninguna de sus
trece obligaciones. Ademas faltaba `proveedor_modelo` en la lista declarada, asi
que un proveedor de modelo de uso general no podia decir que lo era en ninguna
pantalla aunque cinco obligaciones del catalogo lo nombren.

Renombrar en los tres sitios arregla hoy y se vuelve a romper con el cuarto. Lo
que impide que vuelva a pasar es que solo haya una definicion y que el resto se
GENERE de ella, con una puerta que regenera y compara. Si alguien edita el Go a
mano, la puerta se pone roja con el nombre del fichero delante.

Los derivados se versionan en el arbol, no se construyen al vuelo: el lado Go
tiene que compilar sin Python delante, y el panel tiene que poder construirse
sin el motor instalado.

USO:  python herramientas/generar_roles.py            escribe
      python herramientas/generar_roles.py --comprobar  solo dice si hay diferencia
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

RAIZ = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(RAIZ / "motor" / "src"))

from actaira_motor.roles import ROLES, a_contrato  # noqa: E402

DESTINO_GO = RAIZ / "plataforma" / "api" / "roles_generado.go"
DESTINO_PANEL = RAIZ / "panel" / "roles.json"


def go() -> str:
    lineas = [
        "// Code generated by herramientas/generar_roles.py. DO NOT EDIT.",
        "//",
        "// La lista de roles del Reglamento vive en",
        "// `motor/src/actaira_motor/roles.py` y este fichero se genera de ella.",
        "//",
        "// Estaba escrita a mano aqui y estaba MAL: decia",
        "// `responsable_del_despliegue` y `fabricante_de_productos` donde el motor",
        "// dice `responsable_despliegue` y `fabricante_producto`, y le faltaba",
        "// `proveedor_modelo` entero. Como esta lista era ademas la validacion de",
        "// entrada de la API, el efecto no era rechazar el rol equivocado: era",
        "// ACEPTARLO y pasarselo al motor, que no lo reconocia y devolvia cero",
        "// obligaciones aplicables. La validacion confirmaba el error en vez de",
        "// cazarlo, que es lo peor que puede hacer una validacion.",
        "",
        "package api",
        "",
        "// RolesDelReglamento son los identificadores de rol que el motor entiende.",
        "// El orden es el de la fuente y se mantiene para que el diff sea legible.",
        "var RolesDelReglamento = []string{",
    ]
    # El comentario va en su PROPIA linea y no detras del valor. `gofmt` alinea
    # en columna los comentarios finales de entradas consecutivas, asi que
    # ponerlos ahi obligaria a reproducir aqui las reglas de alineacion de
    # gofmt para que el fichero generado salga ya canonico. La puerta de
    # aceptacion corre `gofmt -l` y se pone roja si no lo esta, y el generador
    # no puede llamar a `gofmt` porque no puede depender de que `go` este
    # instalado en la maquina que genera.
    for k, v in ROLES.items():
        lineas.append(f'\t// {v["es"]} (articulo {v["articulo"]})')
        lineas.append(f'\t"{k}",')
    lineas += [
        "}",
        "",
        "// RolConocido dice si el identificador esta en el vocabulario.",
        "func RolConocido(rol string) bool {",
        "\tfor _, r := range RolesDelReglamento {",
        "\t\tif r == rol {",
        "\t\t\treturn true",
        "\t\t}",
        "\t}",
        "\treturn false",
        "}",
        "",
    ]
    return "\n".join(lineas)


def panel() -> str:
    return json.dumps(a_contrato(), ensure_ascii=False, indent=1) + "\n"


GENERADOS = {DESTINO_GO: go, DESTINO_PANEL: panel}


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--comprobar", action="store_true",
                   help="no escribe: sale 1 si algun derivado no es el que toca")
    a = p.parse_args()

    distintos = []
    for destino, hacer in GENERADOS.items():
        nuevo = hacer()
        viejo = destino.read_text(encoding="utf-8") if destino.exists() else None
        if viejo == nuevo:
            continue
        distintos.append(destino.relative_to(RAIZ).as_posix())
        if not a.comprobar:
            destino.parent.mkdir(parents=True, exist_ok=True)
            destino.write_text(nuevo, encoding="utf-8", newline="\n")

    if a.comprobar:
        if distintos:
            print("derivados desfasados: " + ", ".join(distintos))
            print("corre `python herramientas/generar_roles.py`")
            return 1
        print(f"{len(GENERADOS)} derivados al dia")
        return 0
    print(("escritos: " + ", ".join(distintos)) if distintos
          else f"{len(GENERADOS)} derivados ya estaban al dia")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
